FRAMES_PER_SECOND = 60

# Measurements
# All lane, ball, pin measurements are in inches (to align with industry standards)
LANE_WIDTH = 41.5
GUTTER_WIDTH = 9.25
ALLEY_WIDTH = LANE_WIDTH + GUTTER_WIDTH * 2
LANE_LENGTH = 65 * 12  # 90 feet TODO: Needs to be checked
APPROACH_LENGTH = 15 * 12  # 15 feet
LEFT_BOUNDARY = -(LANE_WIDTH / 2)
RIGHT_BOUNDARY = (LANE_WIDTH / 2)

# TODO: Change these to be more accurate later
FOUL_LINE_TO_FRONT_PIN_DISTANCE = 60 * 12  # 60 feet
FOUL_LINE_TO_END_DISTANCE = None
PIN_SPACING_H = 12
HALF_PIN_SPACING_H = PIN_SPACING_H / 2
PIN_SPACING_V = 20.75 / 2
# FOUL_LINE_TO_FRONT_PIN_DISTANCE = 55 * 12  # 60 feet
# PIN_SPACING_H = 12
# HALF_PIN_SPACING_H = PIN_SPACING_H
# PIN_SPACING_V = 20.75

# Colours
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
LIGHT_BLUE = (173, 216, 230)
BUTCHER_BLOCK = (190, 172, 76)

# Dimensions
SCREEN_WIDTH = 720
SCREEN_HEIGHT = 1024 - 32
ALLEY_SCREEN_HEIGHT = SCREEN_HEIGHT
ALLEY_SCREEN_WIDTH = ALLEY_SCREEN_HEIGHT * (LANE_WIDTH / LANE_LENGTH)
